version: "3.7"
services:
  api-mysql:
    container_name: api_mysql_s_batch
    image: marcosmvrg/mysql_s_batch
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3306:3306"
    expose:
      - 3306    
    environment:
      MYSQL_USER: d_s_batch
      MYSQL_PASSWORD: dMo0aXP4Zh24CupI
      MYSQL_DATABASE: s_batch
      MYSQL_ROOT_PASSWORD: Yd0Hiz@Yd4zaB@pyHkanTAR%3rIK
      MYSQL_HOST: localhost
      TZ: America/Sao_Paulo  