version: "3.7"
services:
  batch-mysql:
    container_name: batch_mysql
    image: marcosmvrg/batch_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3307:3306"
    expose:
      - 3306    
    environment:
      MYSQL_USER: d_s_batch
      MYSQL_PASSWORD: dMo0aXP4Zh24CupI
      MYSQL_DATABASE: s_batch
      MYSQL_ROOT_PASSWORD: Yd0Hiz@Yd4zaB@pyHkanTAR%3rIK
      MYSQL_HOST: localhost
      TZ: America/Sao_Paulo  
  app-mysql:
    container_name: app_mysql
    image: marcosmvrg/app_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3308:3306"
    expose:
      - 3306    
    environment:
      MYSQL_USER: d_s_batch
      MYSQL_PASSWORD: dMo0aXP4Zh24CupI
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: Yd0Hiz@Yd4zaB@pyHkanTAR%3rIK
      MYSQL_HOST: localhost
      TZ: America/Sao_Paulo      